version: 2

jobs:
  docs-build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Build docs
          command: mkdir docs
      - run:
          name: copy docs
          command: cp -pdr images paths resources LICENSE docs/
      - run:
          name: create index
          command: cp README.md docs/index.md
      - persist_to_workspace:
          root: .
          paths:
              - docs
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "dsi-ext@zenika.com"
            git config user.name "Zenika"
      - add_ssh_keys:
          fingerprints:
            - "68:2a:57:0b:29:34:b9:94:d8:f6:3c:9f:e4:4b:13:79"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/
workflows:
  version: 2
  build:
    jobs:
       - docs-build:
            filters:
               branches:
                 only:
                    - circleCI
       - docs-deploy:
           requires:
              - docs-build
           filters:
               branches:
                  only:
                      - circleCI