version: 2

jobs:
  docs-build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Build docs
          command: mkdir docs toDeploy
      - run:
          name: copy docs
          command: cp -pdr images paths resources README.md LICENSE docs/
      - persist_to_workspace:
          root: ./toDeploy
          paths:
              - ../docs
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: toDeploy/docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "dsi-ext@zenika.com"
            git config user.name "Zenika"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist toDeploy/docs/
workflows:
  version: 2
  build:
    jobs:
       - docs-build:
            filters:
               branches:
                 only:
                    - circleCI
       - docs-deploy:
           requires:
              - docs-build
           filters:
               branches:
                  only:
                      - circleCI